### ISSUE TITLE
Autolabeler has stopped working in apache/spark and apache/iceberg repos.

### ISSUE THREAD

**Issue by kbendick** [mithro/autolabeler#57]
Hi @mithro! Thank you so much for the wonderful PR autolabeler. 🙂 

I work over on the Apache Iceberg project, and it appears that our autolabeler stopped working around 11 days ago. I checked the Apache Spark repo, which also uses this same autolabeler, and it looks as though the last time their autolabeler ran was about 10 days ago.

I admittedly don't have full access rights over there (the ASF infra team enabled it for us after we put in the config), so I tried opening a PR against my local fork where I do have full control and it also did not seem to run or generate any labels.

Here's the [issue related to this in the Iceberg project](https://github.com/apache/iceberg/issues/1583).

Additionally, here's [our config file](https://github.com/apache/iceberg/blob/master/.github/autolabeler.yml) in the official Apache Iceberg repo.

Finally, here's [a link to the PR I opened in my own fork](https://github.com/kbendick/iceberg/pull/19) where I verified that the autolabeler did not run. The PR in question should have been labeled `FLINK`.

I will attach a screenshot of my forked repos configuration for this app to help debug.

We love having out PRs labeled, so any assistance or tips you could provide would be of great help. I'd be happy to also follow any troubleshooting steps in my local fork, where I have full permissions to adjust whatever I want, if you think that would help.

Thank you for the work you do on this project!

**Comment by kbendick** [comment]
Here's a screenshot showing that the autolabeler is installed in my personal fork.

![image](https://user-images.githubusercontent.com/9833362/95693733-b4df9c80-0be2-11eb-80d7-9ffc657dd10f.png)

**Comment by kbendick** [comment]
And here's a screenshot of the Probot Autolabeler configuration in my local fork. You can see it has all of the permissions that it needs.

![image](https://user-images.githubusercontent.com/9833362/95693801-0a1bae00-0be3-11eb-8179-8a318d97a5a6.png)

**Comment by mithro** [comment]
@kbendick - I believe GitHub has depreciated the API uses by this Robot and I don't have any time to move it to the new API.

**Comment by kbendick** [comment]
Ok. Thank you for your hard work @mithro!

**Comment by Gabitchov** [comment]
Even updating to the last version of Probot version, this update doesn't seem to fix it. @mithro How can I help to debug/find issue in deployment environment?

**Comment by mithro** [comment]
Thanks to @Gabitchov's work the bot is back up and working now!
